### ISSUE TITLE
Error trying to view TGA graphic files

### ISSUE THREAD

**Issue by Frozsoul2019** [sirjuddington/SLADE#1011]
**SLADE Version**: (3.1.4)
**Operating System**: (Windows)

**Issue Details**:
SLADE correctly identifies TGA graphic files as "Graphic (TGA)" and it is stated as a supported data format.  However if you click on a TGA file to view it within SLADE, it results in the error "Error loading entry: Entry is not a known image format".  The issue is not with the TGA file itself as it displays fine when viewed in other programs such as GIMP.

In case it is helpful, the TGA files I am referencing are included in the map WAD files generated by Oblige version 7.70:
http://oblige.sourceforge.net/i_download.html

**Comment by sirjuddington** [comment]
Do you mean the tga files that come with oblige (in the 'data' folder)? If so, I can't reproduce the issue with them, they open fine for me.

**Comment by Unstabler2018** [comment]
No, I mean the TGA files that are automatically included in the WAD files that are generated by running the Oblige program, which creates randomly-generated DOOM maps.  Attached is an example of a single-map WAD file that I generated using Oblige version 7.70 that includes the TGA files INTERPIC and TITLEPIC.  When I open the WAD file in SLADE and click on either of these files I get the error message "Error loading entry: Entry is not a known image format".  However if I export the TGA files they open fine in other programs such as GIMP.

Because Github does not permit WAD files to be attached I have zipped the example WAD file:
[Oblige-7.70-Original.zip](https://github.com/sirjuddington/SLADE/files/2759514/Oblige-7.70-Original.zip)

**Comment by sirjuddington** [comment]
Ok I see now, when I generated one I didn't select GZDoom so the TITLEPIC etc were doom format gfx.

Unfortunately it looks like this is an issue with FreeImage (it doesn't detect that they are TGA even though they are), not much I can do about it without writing my own TGA reader or using a different lib

**Comment by Frozsoul2019** [comment]
Good news - it looks like this issue is fixed as of SLADE 3.1.6!

**Comment by sirjuddington** [comment]
Ok that's good, 3.1.6 uses a newer version of FreeImage so I guess they fixed it in that
