### ISSUE TITLE
Text (JASC/GIMP) palette imports broken

### ISSUE THREAD

**Issue by DasyatidPrime** [sirjuddington/SLADE#1095]
**SLADE Version**: 3.1.8
**Operating System**: Windows, confirmed in Linux

**Issue Details**:
Hi! I found on SLADE 3.1.8 that trying to import JASC or GIMP text format palettes into a PLAYPAL entry would fail every time with "invalid header". Having looked at the code in `src/Graphics/Palette/Palette.cpp` in master, it seems like the text palette import was using Tokenizer in a way that would cause it to process tokens at the wrong positions sometimes.

I have a draft quick-fix patch for this in my [rtt2019-palettefix-1 branch](https://github.com/DasyatidPrime/SLADE/tree/rtt2019-palettefix-1), which I based on master (and could rebase to stable if desired for a PR). It also tweaks the CSV palette parsing, which seems to have had a similar problem. My big qualm with all this is that the Tokenizer interface itself seems pretty inconsistent about both (a) whether a consumer is “looking at” `token_current_` or `token_next_` at any given time and (b) whether combined test-and-advance and fetch-and-advance methods advance before the test/fetch or after it—which means the quick fix creates more of a mess at the interface boundary. I also think it would probably be better to have the different text palette parsing modes be in separate functions, rather than treating the three syntaxes as inline variants of the same one.

If cleaning up the Tokenizer method interface is something you'd accept, I'd be willing to go scan for other uses of it and try to make everything consistent. And if you'd like the split-up parsing functions and/or better CSV handling, I can do that separately.

What do you think?

**Comment by sirjuddington** [comment]
Yeah I can understand the tokenizer could be a bit confusing to others :P, however I have it written as I'd like to use it for the most part so would rather it be left alone for now (though I'm still not 100% happy with it).

The palette parsing stuff was never properly converted over to the 'new' tokenizer when I reworked it a while ago which is why it's a bit messy there. You'll notice in `Tokenizer.h` a bunch of functions are commented as bridge functions from the old tokenizer interface that shouldn't be used - anything using these still needs to be converted over to use the 'new' stuff, I just haven't got around to it yet.

That said, I do have a WIP local branch with a new tokenizer that simply tokenizes everything at the start into a bunch of `string_view`s now we're using c++17, which makes things a bit simpler on the user end (can just keep track of the current token index etc. yourself and get tokens via an index operator eg. `tz[current_index]`).
