### ISSUE TITLE
IWD Support

### ISSUE THREAD

**Issue by ghost** [sirjuddington/SLADE#1119]
It would be nice Slade supported the IWD File type 
https://file.org/extension/iwd

**Comment by Gaerzi** [comment]
I don't see any actual specifications on your link. It does say, however, they can be opened by WinRAR, so it's probably just a standard format with a special extension, like how pk3 are just zips. If so, they can probably already be opened.

Otherwise, I feel the game is kinda out of scope for SLADE. It's more about 90s games.

**Comment by Leo40Git** [comment]
...according to your link, that format is for CoD 2 and 4. Correct me if I'm wrong, but those are not Doom engine games.
Did you mean [IW*A*D](https://doomwiki.org/wiki/IWAD), by any chance?

**Comment by goldenmob72** [comment]
> ...according to your link, that format is for CoD 2 and 4. Correct me if I'm wrong, but those are not Doom engine games.
> Did you mean [IW_A_D](https://doomwiki.org/wiki/IWAD), by any chance?

Nope

**Comment by sirjuddington** [comment]
According to [this](http://modsonline.com/Tutorials-read-333.html) it's just a zip file, so it could just be added to the list of pk3 extensions I guess
