### ISSUE TITLE
When in 3D view, scrollwheel inputs are sometimes registered twice

### ISSUE THREAD

**Issue by iirelu** [sirjuddington/SLADE#1216]
**SLADE Version**: 3.2.0 beta 1
**Operating System**: Linux

**Issue Details**:
When in 3D mode, scrolling to raise/lower floors/ceilings ends up moving them by 8 units twice, instead of just once. The output in the top left confirms this, as it looks like this after repeatedly scrolling down one notch and scrolling up one notch:
![image](https://user-images.githubusercontent.com/3432543/98398717-b1b0c280-2061-11eb-94b8-41d6a54b9cc2.png)

The keyboard shortcuts assigned to the same task do not suffer from this problem. Pressing Numpad Plus and Numpad Minus only raises/lowers once, as expected. Other scrollwheel inputs outside of 3D view, like zooming and scrolling, also work fine.

**Comment by NovaSilisko** [comment]
Sorry if I'm putting this in the wrong place, I don't get out into the public part of github much...

I also am on Kubuntu (21.04) and have been recently annoyed by this issue myself, and have been poking at it since I've been playing with the source a bit too. It really seems like wxWidgets is just putting out two near-simultaneous mouse wheel events, but I am utterly unfamiliar with wxWidgets so that's about as far as I can take that thought.

As a super sloppy workaround, I just added a variable to keep track of the last mouse wheel event time (from app::runTimer()), and ignore any that are too close together. I also made it log the delta time between wheel events and as you can see the second one usually happens within <10 ms(?) of the previous, usually small enough to report as 0. 

![2021-09-02_11-12-28](https://user-images.githubusercontent.com/3247833/131869934-3280edfe-6680-4a2c-b066-960c75f2a3cf.png)

At least here, it definitely doubles up ALL mouse wheel events though, not just in the 3D view. 

I don't know if any of this will be of any use, but I figured I might as well report it for the 17 whole SLADE linux users out there affected by this problem.

(originally posted in #1246 but this is the one that's open so I moved my post over here)

**Comment by man-of-eel** [comment]
For me (Ubuntu 18.04) it registers once as it should but only the first time I move the wheel down after entering 3d view. Every subsequent movement registers as two.

**Comment by NovaSilisko** [comment]
As I mentioned when trying to help investigate another thing, I accidentally solved the wheel doubling issue for myself by switching to another computer... Same OS, same CPU family (ryzen 1700 vs ryzen 2200G) the main difference though is both software installed (the first one I was trying is my development machine, so it has a substantial amount of stuff on it) and the GPU. In the other case, it was a GTX 1070, while in this case, it's the AMD integrated GPU of the 2200G. In general, SLADE runs much better on this much weaker system, somehow. I have no idea if this finding will be of any use, but it's there for consideration, at least...

**Comment by eevee** [comment]
I reproduced against a minimal sample, so this is definitely a wxGTK bug.  Filed wxWidgets/wxWidgets#23383.

FWIW with the workaround, you don't need to fudge it with a delta; `e.GetTimestamp()` appears to be exactly the same between both firings, every single time.
