### ISSUE TITLE
Mouse wheel events are usually executed twice in 3D mode

### ISSUE THREAD

**Issue by ruben3d** [sirjuddington/SLADE#1246]
**SLADE Version**: (3.1.12) Installed from Ubuntu repo
**Operating System**: (Kubuntu 20.04 x64)

**Issue Details**:
When trying to adjust the height of floors or ceilings in 3D mode using the mouse wheel the action happens usually twice, and on some occasions only once. So a single mouse wheel event will display two entries on screen about adjusting the height by 8 units, resulting in a total offset of 16 units. Same with Shift+Wheel, it triggers two 1 unit events, resulting in a total cumulative of 2 units. It's annoying as when the odd event happens (just one instead of two) moving up or down won't end in the same position it was before, as most of the subsequent events will always be double. Single events are usually at the start of a sequence of events (but not all the sequences start with single events), while always double events follow. As a workaround I use the numpad keys. 

I have tried reproducing the same issue with a js event handler in the browser, just in case it is related to the mouse itself, driver or system settings, but it appears to work correctly, just one mouse wheel event per wheel tick.

**Comment by sirjuddington** [comment]
Yeah this is a known issue - see #1216 

Will close this one

**Comment by NovaSilisko** [comment]
Sorry if I'm putting this in the wrong place, I don't get out into the public part of github much...

I also am on Kubuntu (21.04) and have been recently annoyed by this issue myself, and have been poking at it since I've been playing with the source a bit too. It really seems like wxWidgets is just putting out two near-simultaneous mouse wheel events, but I am utterly unfamiliar with wxWidgets so that's about as far as I can take that thought.

As a super sloppy workaround, I just added a variable to keep track of the last mouse wheel event time (from app::runTimer()), and ignore any that are too close together. I also made it log the delta time between wheel events and as you can see the second one usually happens within <10 ms(?) of the previous, usually small enough to report as 0. 

![2021-09-02_11-12-28](https://user-images.githubusercontent.com/3247833/131869934-3280edfe-6680-4a2c-b066-960c75f2a3cf.png)

At least here, it definitely doubles up ALL mouse wheel events though, not just in the 3D view. 

I don't know if any of this will be of any use, but I figured I might as well report it for the 17 whole SLADE linux users out there affected by this problem.
