### ISSUE TITLE
can't save the changes because of a "duplicate"  named sprites

### ISSUE THREAD

**Issue by Nightmarekiller84** [sirjuddington/SLADE#1345]
slade_3.2.0_x64
Operating System - Windows 7

For whatever reason, any changes I make in the files of a wad or pk3, sometimes I can't save the changes because of a "duplicate" 
named sprite. For example if there is a E1m1.png twice but different, I can't save because of that, this is a new problem for me and never had happened before. i test it again with older versions and was fine

**Comment by Blzut3** [comment]
More than likely you're running into an intentional change.  It's malformed to have a pk3 with duplicate entries.  If one creates such a file then only one of the duplicates will be loaded by the engine and which one is loaded will be undefined and potentially change based on compiler used to build the game engine.  Slade is just now able to tell you that your mod is broken instead of being told by players that your mod is magically not working for them.
