### ISSUE TITLE
File name syntax parsing issue

### ISSUE THREAD

**Issue by MajorCooke** [sirjuddington/SLADE#1378]
**SLADE Version**: 3.2.1
**Operating System**: Windows

**Issue Details**:
If you have a file named **Modeldef.txt**, the syntax upon clicking the file will be properly highlighted. 

But if you have a file named **ModelDef.Armor.txt**, the letters for key words and syntax does **not** work. Everything is black, except for what's in quotations.

**Comment by Blue-Shadow** [comment]
That file's name is `ModelDef.Armor`, not `ModelDef`, which is why it isn't recognized as a MODELDEF file; it's entirely different name.

You can fix it by removing the `.txt` from the end of the name so that `.Armor` becomes the extension.

**Comment by MajorCooke** [comment]
Which is odd because this was never a problem in 3.1.x. Now it is an issue.

**Comment by sirjuddington** [comment]
It's because previously everything after the first `.` in an entry/file name was considered the extension, but now it's only after the last `.`

It was changed so that something named eg. `file.name.txt` would be properly detected as text.

I think to fix both situations I might change it (at least for type detection) that only text before the first `.` is considered part of the entry name. Or possibly just implement #141
