### ISSUE TITLE
Issues with FLAT format conversion

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [sirjuddington/SLADE#1603]
(Version 3.2.4, Windows)

From my experience, Flats are really weird to convert. Whenever I try to convert something to a Flat (be it in PNG or Doom Graphic format), SLADE has trouble recognizing it (showing up as either "Unknown" or "Jaguar Tx"). When converting Flats to another format, they either come out as "Unknown" or are garbled. What could be causing this?

**Comment by sirjuddington** [comment]
If you're converting something to a Flat, it needs to be within the flats namespace (flats dir for pk3 or between F_START and F_END markers for wad) or it can't be detected. Converting from flat to something else should work fine though, just tried it then with a few flats and it worked each time.

**Comment by PerdGateEnjoyer** [comment]
I feel like I should be able to convert a graphic to FLAT without having it in the F_START-F_END section, so I could convert it first then place it there.

**Comment by Gaerzi** [comment]
Flats are raw data. There's nothing to identify them with except their size and their presence in the proper namespace. And using just the size caused too many issues with things that aren't flats being identified as flats.

If you convert outside of the proper namespace, you get a flat, but it won't be recognized as such because it won't be in the proper namespace. You can still move it there, though, if you prefer to do convert-then-move instead of move-then-convert.
