### ISSUE TITLE
96000 Hz sounds break when converted to Doom Format

### ISSUE THREAD

**Issue by mallo15** [sirjuddington/SLADE#227]
48000 Hz sounds convert just fine but 96000 Hz sounds get slowed down and pitched way down so they sound like something out of Doom64 :/ You could at least put a "96KHz frequencies unsupported!" message or convert them to 48KHz first or something. That'd be neat. Thanks in advance.

**Comment by Gaerzi** [comment]
I'm a bit surprised you managed to find an 8-bit 96khz sound in the first place... (Only 8-bit sounds can be converted to Doom format sounds.)

If you can provide the sound in question, I'll see what I can do with it.

**Comment by mallo15** [comment]
I just exported it in Audacity as uncompressed with WAV header and unsigned 8-bit coding with Project's rate being 96000Hz. (The sound is my mouth making an explosion sound btw)
https://dl.dropbox.com/s/h4llvadggxfp706/lel.wav?dl=0

**Comment by Gaerzi** [comment]
Okay. It's kinda dumb, but the reason is obvious: DMX sound format uses two bytes each to store sample count and sample rate, so the maximum value is 65535. So when you have a file that has 181673 (0x2C5A9) samples at 96000 Hz (0x17700) and you convert it to DMX, the values that get written are 50601 (0xC5A9) samples at 30464 Hz (0x7700).

**Comment by mallo15** [comment]
Couldn't it get converted down to like, 48000Hz first tho?

**Comment by Gaerzi** [comment]
That would involve actually changing the samples, instead of merely changing the header. If SLADE could do that, it could also convert sounds with several channels, more than 8-bit per sample, etc.
