### ISSUE TITLE
OSX: Title bar positioning issue

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#263]
"Double-clicking on the title bar makes the window stick to the upper left hand corner of the desktop and more importantly hides the title bar - it might be underneath the menu, but I don't think so.  Only way I could get the title bar back was to delete my config."

See [this thread](http://mancubus.net/forums/index.php/topic,1866.msg0.html) for further information.

**Comment by alexey-lysiuk** [comment]
I cannot reproduce this using 3.1.0.2 and 3.1.0.3 built from my fork (wxWidgets 3.0.0) nor using a18f7aa170 built with CMake from Homebrew (the latest wxWidgets built from sources, https://github.com/wxWidgets/wxWidgets/commit/39b9a6bbeb1aaff25621b7bbbeaf678bc3974819).
Also, the dock preferences don't introduce the given effect: double-clicking does nothing by default and window is minimized if the corresponding option is enabled.
I think, the bug may be caused by some third-party software or by very specific combination of OS settings.

**Comment by sirjuddington** [comment]
What version of OSX are you running? It happens to me on my VM with Yosemite installed.

**Comment by alexey-lysiuk** [comment]
I'm running 10.10.3.
