### ISSUE TITLE
Generated map PNGs should not contain grAb chunk

### ISSUE THREAD

**Issue by haleyjd** [sirjuddington/SLADE#295]
SLADE appears to add a ZDoom grAb chunk to any PNG that it outputs, including its map image files. As a result, several hundred images on the Doom Wiki now contain this non-standard chunk, which some tools (such as ImageMagick) complain about causing a CRC mismatch.

grAb should only be a factor for resources, and should only be either preserved when already present, or added when saving out a resource with offsets. Generated map images have no reason to have offsets in them.

**Comment by Blzut3** [comment]
Without looking, my assumption would be the CRC mismatch is caused by the CRC being calculated incorrectly.  Presumably that's a bigger issue than including the grAb chunk, although I can agree with the logic that it's pointless to include it for those images (or any image with 0,0 offsets for that matter).
