### ISSUE TITLE
3.1.1 slope issues

### ISSUE THREAD

**Issue by Gaerzi** [sirjuddington/SLADE#334]
See [this thread](http://forum.zdoom.org/viewtopic.php?f=2&t=49755) and [this file](http://afadoomer.com/trek/files/Slope%20Offset.pk7) (that you will first have to transform to a standard zip to open with SLADE).

![Result](http://i.imgur.com/6PqQaUa.png)

**Comment by eevee** [comment]
Fascinating!  The .pk7 doesn't run because (I think?) ZDoom is choking on the DOS line endings, and extracting to a folder doesn't work correctly because ZDoom doesn't recognize `Textures` as a texture namespace (even though it recognizes `Maps` as a map namespace).

The actual problem in the map: it uses UDMF vertex height properties, but leaves some of the ceiling heights unspecified.  SLADE doesn't distinguish between a missing property and a property with its default value, which for integers is zero, so it looks like two of the ceiling vertices are _supposed_ to be on the floor.

I don't know how to fix this.  It seems like a fundamental limitation of the map object property system.  There's no way to display a "missing" value in the prop grid or "delete" a value, either — and wx's "unspecified" state is already in use for multi editing.

**Comment by sirjuddington** [comment]
Fixed the slope issue at least, though there are other issues with this map (texture scaling/alignment is completely wrong, for one)
