### ISSUE TITLE
Directories and ZIP archives should be listed in alphabetical order

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#403]
According to [the ZDoom wiki](http://zdoom.org/wiki/Using_ZIPs_as_WAD_replacement), the order for a zip/dir is _always_ to load everything in (case-insensitive) alphabetical order, with embedded WADs coming last.

I think this would also fix the map dialog for directories, which currently lists map in nonsense order.

Rearranging items should also be disallowed, especially for directories where there's no such thing.

**Comment by Gaerzi** [comment]
Note that the ZDoom wiki lists the behavior of ZDoom. I don't believe SLADE should always align itself entirely on ZDoom, as it has a more general purpose than being a ZDoom editor.

But if it's optional, then okay.

**Comment by eevee** [comment]
Hm.  What other ports support zip files, and what's their behavior?

**Comment by Gaerzi** [comment]
Doomsday, Vavoom, Eternity. I don't know about their behaviors in detail; but I like that SLADE will show me zipped files in their actual physical order because that's something you need a hex editor to find out otherwise. Most zip utility will sort their display. And also, most zip utilities will overwrite foobar.baz when you add another foobar.baz in the zip archive, even though the zip format is perfectly able to contain several files with the same name, and SLADE will handle such a situation correctly.

**Comment by eevee** [comment]
Fair enough.  What if archives had an optional "order" column, and you could click the column headers to change the (displayed only, not physical) sort order?

Duplicated files is pretty interesting — I take it ports will correctly load both files in the order they appear?

I can't find documentation on the other other ports load files, but I'm also not sure they load nested wads, which is probably the only time order would matter in practice.

**Comment by Gaerzi** [comment]
You can already sort the display. Click on the name, size, or type column. Partly because of that, and [partly because some vanilla error messages refer to lump numbers](
http://doomwiki.org/wiki/Error_message#WAD_file_errors), I've added index number to the display on the status bar and on the generic entry panel display.

**Comment by eevee** [comment]
Huh.  I swear I've tried that before and it didn't work, but it looks like it was added a year and a half ago.

Maybe all there is to do here, then, is:

- Treat directories' natural order as alphabetical with root WADs last, since the "order" of a directory is mostly meaningless and unchangeable.  (This is a very ZDoom-inspired behavior, granted, but I'm not sure directories or embedded WADs are even supported by other ports, and it's not an unreasonable default anyway.)
- Move "Sort" from the Entry menu to the Archive menu, where I can actually find it  :)  And maybe it should sort subdirectories as well?
- Figure out how to put chevrons on sorted column headers.

**Comment by sirjuddington** [comment]
The 'sort' menu option is a tricky one, since it kind of fits in both the 'Archive' and 'Entry' menus, depending on the current selection (if multiple entries are selected it will only sort the selection, so here it makes sense to be in the 'Entry' menu).

When I added the entry list sorting stuff, wxListCtrl chevrons were only supported in wxMSW, which I assume is still the case.

**Comment by sirjuddington** [comment]
Closing this one since I think it's mostly solved in 3.2.0 (at least UI wise)
