### ISSUE TITLE
Behavior of createThing is totally unintuitive

### ISSUE THREAD

**Issue by eevee** [sirjuddington/SLADE#490]
I have, more than once, maybe more than a dozen times, accidentally created tons of things with a Z offset or special or TID that they weren't intended to have.  I never understood why this only _sometimes_ happened, until I looked at the source code just now and found that thing properties are taken from the selection or highlight.

This is consistent with how creating a new sector (with `Insert`) works, but in the case of things, it's unnecessary — if you want to duplicate a thing, just copy and paste it.  So I propose that a thing created by `Insert` should only inherit its type (which is clearly visible on the map!) from the `copy_thing`, and not any of the various other less-visible properties.

**Comment by Gaerzi** [comment]
What about the angle? Like the type, it's also clearly visible (except for actors where angle is irrelevant).

**Comment by eevee** [comment]
Angle definitely makes sense too.

Occasionally I've worked with polyobjs and then ended up creating bunches of monsters and pickups whose angles were 1, but that's pretty minor  :)

**Comment by sirjuddington** [comment]
It doesn't have anything to do with the selection/highlight - it uses the previously copied thing properties (`copy_thing` in `MapEditor`). What you might be seeing though, is the properties of the previously edited thing, since 'modify properties' for things will also update `copy_thing`.

I'll change this so it only uses the type and angle, not all properties. I'd like for it to copy flags as well, but that is tricky to do for UDMF without just copying all properties as it does currently.
