### ISSUE TITLE
"^" Character not supported for WADs ?

### ISSUE THREAD

**Issue by LordOZ98** [sirjuddington/SLADE#682]
**SLADE Version**: 3.1.1.5
**Operating System**: Windows

**Issue Details**:
Can't use those on lump names inside WADs, Slade keeps making them "\"

**Comment by Gaerzi** [comment]
Edit->Preferences->Editing->Use percent encoding.

The ^ is an odd case because by default SLADE uses the ZDoom-compatible method of replacing the \ character with ^ when a lump with that in the name is copied outside of a WAD file. And so naturally, when a lump with the ^ character is inserted in a WAD file, the reverse operation happens and it's replaced with a \ . If you enable the percent encoding system instead, then \ is converted to %5c instead (IIRC) and it's %5c that gets replaced with \ so you can use ^ in WAD file without them getting renamed.

**Comment by LordOZ98** [comment]
I did what you said, But still it gets renamed ?
