### ISSUE TITLE
Create an official portable Linux distribution

### ISSUE THREAD

**Issue by Calinou** [sirjuddington/SLADE#713]
It would be nice to have an official portable Linux distribution, so that one can use SLADE even if it's not in their distribution repositories. The goal is to be able to run SLADE on any Linux distribution that's not very old (like, released after 2014 or so), without having to install any libraries or compile anything.

[AppImage](http://appimage.org/) or [Flatpak](http://flatpak.org/) are two potential solutions that can be used for this. I tend to have a preference for AppImage, mostly because it can be made to work on old distributions easier (from what I've heard; I don't have actual experience with Flatpak, but Flatpak seems to require a runtime, unlike AppImage which just needs FUSE support enabled). Other benefits of AppImage include:

- optional desktop integration (desktop menu entries),
- optional signing using GPG 2,
- optional delta updates,
- compression support,
- an application is a single file (like macOS's `.app` files), so it's easy to copy/move around,
- …

I can assist in doing this, I've already created AppImages for [Godot Engine](https://godotengine.org/) and [Minetest](http://www.minetest.net/). Many projects also officially use and support AppImages for their Linux distributions, such as [Krita](https://krita.org/).

___

Pinging @probonopd on this, since he is the AppImage lead developer.

**Comment by sirjuddington** [comment]
I'm certainly not against something like this if someone is willing to set it up :P Ideally some kind of script I can run to build the AppImage or Flatpak when making a release

**Comment by probonopd** [comment]
We could reuse binaries from the [DRD Team Package Repository](http://debian.drdteam.org/) which is great because it is compiled against Ubuntu 12.04 LTS:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/SLADE.yml

The following will build an AppImage from the latest available deb in the repository:

```
wget -c https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe
bash -ex Recipe SLADE
```

An example AppImage can be downloaded from
https://bintray.com/probono/AppImages/Slade#files

It is expected that some fine-tuning may be required.

**Comment by probonopd** [comment]
@sirjuddington does it work for you?

**Comment by sirjuddington** [comment]
Yeah that worked :), a few issues though:
* After selecting to add a desktop menu entry, the entry has no icon
* The desktop menu entry should be in all caps (since SLADE is _technically_ an acronym)
* Using the build from the drd team repository isn't ideal:
  * It is built without wxWebView support, which disables a few features and uses the 'basic' start page (ie. it isn't the intended experience)
  * As I'm not the one handling these builds, I won't be able to put up the AppImage for a new release on the website until it is available on the repository

Also another minor nitpick, the icon/logo [here](https://bintray.com/probono/AppImages/Slade#files) is the old SLADE icon

**Comment by probonopd** [comment]
Thanks @sirjuddington 

Please view my AppImage only as an example, I would highly appreciate if you/someone from the upstream project would take over from here.

> After selecting to add a desktop menu entry, the entry has no icon

Probably the correct icon needs to be put into `usr/share/icons/...` inside the AppDir

> The desktop menu entry should be in all caps (since SLADE is technically an acronym)

Can easily be changed in the `.desktop` file

> Using the build from the drd team repository isn't ideal

Is there another repository that has debs for Ubuntu 14.04 or older?
Alternatively, you could build from source, e.g., on Travis CI. Check these examples: https://github.com/search?l=YAML&q=linuxdeployqt&type=Code&utf8=%E2%9C%93

>  the icon/logo here is the old SLADE icon

Again, easy to change by changing the package or the yml file
>

**Comment by Alexander-Wilms** [comment]
I created a Flatpak manifest here: https://github.com/Alexander-Wilms/flathub/tree/slade

This also includes wxWebView support, but building webkitgtk takes quite some time.
