### ISSUE TITLE
Don't allow saving pk3s with duplicate entries by default

### ISSUE THREAD

**Issue by Blzut3** [sirjuddington/SLADE#885]
**SLADE Version**: (3.1.2b5)
**Operating System**: Linux

**Issue Details**:
With Zandronum a frequent issue we run into is people hosting mods with duplicate entries in zip files (see https://zandronum.com/tracker/view.php?id=3435 for example).  Since zip archives are assumed to be internally unordered this creates a situation where what happens when the mod is loaded is platform dependent.  Per issue #403 Slade preserves as much state from the archive as possible and while I personally think this is a decent idea it does makes this error easy to make.

My suggestion is to have Slade scan for duplicate entries and show an error prompt on saving until the duplicate is addressed.  Like with the iwad lock this could be overridden by a console variable if for some reason creating such an archive is actually desirable.

I do believe this is a tooling error rather than a port error as while this could be solved by using stable sorts (possibly changing the behavior of existing mods in the process), ultimately such archives are generally incompatible with normal zip archiving software so I would still consider such archives undefined/malformed.

**Comment by NerduMiner** [comment]
This feature breaks certain pk3's made for Sonic Robo Blast 2 and its derivatives. Sonic Robo Blast 2 supports sprite sets with up to 64 frames, which means any sprite set made with more than 35 frames will be caught by the duplicate check(frame A(frame 1) and frame a(frame 36) are considered the same). I have also seen pk3s that define an S_SKIN to have both the sprite set for the normal form and the super form in the pk3, which use the same lump names and are differentiated by a marker. In this case, the duplicate check is also validated.

Since both cases take advantage of what seems to be agreed upon malformed formatting of a ZIP archive. I won't pursue a fix to be made. I am also not speaking on behalf of the entire SRB2 community, I just wanted to note down some observations I have made while trying to work with other people's mods who still use SLADE 3.1.13

**Comment by gitdunk** [comment]
It seems this duplicate thing is still an issue for SLADE, I found the "zip_allow_duplicate_names" setting and changing it did nothing for me when trying to save a srb2 pk3.

**Comment by Blzut3** [comment]
That cvar only allows you to load a malformed zip, it doesn't change saving behavior.

If there's not a good solution to using Slade with SRB2 right now then someone involved with SRB2 development should open a new ticket to discuss requirements and possible solutions.  The reality is if you can't use a standard archive tool (7-zip, winrar, whatever) to unpack the zip and pack it again without losing data then half of the reason for using a zip is being defeated.  As a Linux user I can kind of feel for the desire for case sensitive file names, but in my opinion it's kind of a poor solution to the problem.  Note that I'm just a one in a while contributor so I'm just stating a personal opinion here which does not reflect the stance of the Slade project.

That said is there no alternative way to package the mod that doesn't require building a malformed zip?  There are still people contributing SRB2 fixes judging by the git activity here, so not sure if that indicates Slade 3.2 is still a suitable tool and you just need to alter the mod in some way.  (My assumption is that upper/lowercase names can be resolved by simply using a second directory for the lower case sprites.  Not sure what else.)
