### ISSUE TITLE
Issues with "Use percent encoding if needed outside of Wad Archives"

### ISSUE THREAD

**Issue by SteelTitanium** [sirjuddington/SLADE#982]
**SLADE Version**: 3.1.3
**Operating System**: Windows

**Issue Details**:
If the "Use percent encoding if needed outside of Wad archives" setting is enabled, the following happens. 
1: The palette names won't be parsed correctly. 
2: SLADE will still make a new folder for the lump despite being told not too.

**Comment by Gaerzi** [comment]
Could you be more explicit? Give an example of specific lump name that you've encountered the issue with?

**Comment by SteelTitanium** [comment]
As a example, if a lump is named ``ABCD\0``, instead of converting the ``\`` to ``%5C``, a new folder with the original lump name as the name, and the ``0`` part of the name ends up being a new lump within that folder.

**Comment by Gaerzi** [comment]
Okay, so the renaming with that option is broken.

(Turning ABCD\0.png into 0.png in ABCD folder is just a logical consequence of how zip files work. Basically a zipped file consists of a header with filename and some other meta info needed to uncompress it, followed by its compressed data blob. A zip file consists in a string of zipped files glued together one after the other. You can check it out with a hex editor because the file names themselves are not compressed. So "folder/directory/file.ext" is simply named like this (/ and \ being interchangeable) in the zip content, and it's the zip utility that has to interpret it as a file named "file.ext" within "directory" which itself is within "folder". You can even edit that in your hex editor, as long as you don't change any offset (don't change the length of the character string) so if you edit it to "folder-directory_file.ext" you'll get a file in the zip's root folder, with a long name.)

**Comment by Gaerzi** [comment]
What palette names where? The palette selector?

**Comment by Gaerzi** [comment]
Since 972e478 is only a partial fix, let's reopen this.
